# Generated by Django 4.1.7 on 2023-03-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('imdb_ukr', models.URLField()),
                ('duration', models.PositiveIntegerField()),
                ('start_date_right_to_rent', models.DateField()),
                ('end_date_right_to_rent', models.DateField()),
            ],
            options={
                'unique_together': {('title', 'director', 'start_date_right_to_rent', 'end_date_right_to_rent')},
            },
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='cinema_hall.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='screening.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_sold', models.BooleanField(default=False)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='screening.screeningsession')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema_hall.seat')),
            ],
        ),
    ]
