# Generated by Django 4.1.7 on 2023-03-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_hall', '0001_initial'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('screening', 'seat')},
        ),
    ]
