# Generated by Django 4.1.7 on 2023-03-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_hall', '0001_initial'),
        ('screening', '0002_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('screening', 'seat', 'session_date_time')},
        ),
    ]
