# Generated by Django 4.1.7 on 2023-03-24 21:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='facebook_social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='instagram_social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='youtube_social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
