# Generated by Django 4.1.7 on 2023-03-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'row', 'number')},
        ),
    ]
