# Generated by Django 4.1.7 on 2023-03-23 21:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='facebook_social_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='instagram_social_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='cinema',
            name='youtube_social_link',
            field=models.URLField(null=True),
        ),
    ]
